export const libHelperName = {
	addElement: "__addElement",
	createElement: "__createElement",
	createElementNS: "__createElementNS",
	createConditionalElement: "__createConditionalElement",
	createConditionalElementNS: "__createConditionalElementNS",
	createMultiElement: "__createMultiElement",
	createMultiElementNS: "__createMultiElementNS",
	createTextNode: "__createTextNode",
	createExpressionTextNode: "__createExpressionTextNode",
	addAttribute: "__addAttribute",
	addAttributes: "__addAttributes",
	addProperty: "__addProperty",
	addCustomAttribute: "__addCustomAttribute",
	addProperties: "__addProperties",
	addRef: "__addRef",
	addListener: "__addListener",
	addListeners: "__addListeners",
	addShadowRoot: "__addShadowRoot",
	attributeChanged: "__attributeChanged",
	connectFoveaHost: "__connectIFoveaHost",
	connectCustomAttribute: "__connectCustomAttribute",
	dispose: "__dispose",
	registerStaticTemplate: "__registerStaticTemplate",
	useStaticTemplate: "__useStaticTemplate",
	registerProp: "__registerProp",
	registerSetOnHost: "__registerSetOnHost",
	mapPropertiesToAttributes: "__mapPropertiesToAttributes",
	registerElement: "__registerElement",
	registerCustomAttribute: "__registerCustomAttribute",
	registerHostListener: "__registerHostListener",
	registerChangeObserver: "__registerChangeObserver",
	registerAttributeChangeObserver: "__registerAttributeChangeObserver",
	registerVisibilityObserver: "__registerVisibilityObserver",
	registerChildListObserver: "__registerChildListObserver",
	constructCustomAttribute: "__constructCustomAttribute",
	constructFoveaHost: "__constructFoveaHost",
	registerEmitter: "__registerEmitter",
	registerStaticCSS: "__registerStaticCSS",
	useStaticCSS: "__useStaticCSS",
	use: "__use",
	dependsOn: "__dependsOn",
	ICustomAttribute: "ICustomAttribute",
	registerHostAttributes: "__registerHostAttributes",
	destroy: "__destroy"
};

export declare type LibHelperName = keyof typeof libHelperName;