import {Options} from "prettier";
import {IStyleOptions} from "./i-style-options";
import {IStringifyObjectOptions} from "./i-stringify-object-options";
import {IServeConfig} from "./i-serve-config";

export interface IBuildConfig {
	production: boolean;
	development: boolean;
	staging: boolean;
	testing: boolean;
	debug: boolean;
	verbose: boolean;
	srcFolderName: string;
	defaultCssExtension: "scss"|"css";
	defaultScriptExtension: "ts"|"js"|"tsx"|"jsx";
	defaultDestinationScriptExtension: "ts"|"js"|"tsx"|"jsx";
	defaultXMLScriptExtension: "html";
	defaultJsonExtension: "json";
	hashName: string;
	rootComponentName: string;
	homeComponentName: string;
	componentName: string;
	distFolderName: string;
	assetFolderName: string;
	iconFolderName: string;
	appIconName: string;
	appIconExtension: string;
	tsconfigName: string;
	tslintName: string;
	gitignoreName: string;
	npmignoreName: string;
	entryName: string;
	indexName: string;
	serviceWorkerFolderName: string;
	serviceWorkerName: string;
	serviceWorkerWorkboxName: string;
	serviceWorkerCleanupName: string;
	serviceWorkerWorkboxSWName: string;
	serviceWorkerWorkboxInitializeName: string;
	serviceWorkerRoutingName: string;
	serviceWorkerPrecachingName: string;
	serviceWorkerRegisterName: string;
	serviceWorkerChunkPrefix: string;
	serviceWorkerRegisterFunctionName: string;
	stylesFolderName: string;
	manifestName: string;
	baseStylesName: string;
	themeStylesName: string;
	colorStylesName: string;
	fontStylesName: string;
	foveaCliConfigName: string;
	packageFileName: string;
	esmCaniuseFeatureNames: string[];
	webComponentsCaniuseFeatureNames: string[];
	sharedStylesName: string;
	globalStylesName: string;
	formatOptions: Options;
	defaultProjectVersion: string;
	styleOptions: IStyleOptions;
	stringifyObjectOptions: IStringifyObjectOptions;
	environmentFolderName: string;
	environmentFileName: string;
	environmentDefaultsFileName: string;
	cacheRoot: string;
	polyfillUrl: string;
	serveConfig: IServeConfig;
}