export {IHostAttributeValues} from "./decorator/host-attributes";
export {IEmitBaseOptions, IVisibilityObserverBaseOptions, IHostListenerBaseOptions, IMutationObserverBaseOptions} from "@fovea/common";
export {onChange} from "./decorator/on-change";
export {selector} from "./decorator/selector";
export {prop} from "./decorator/prop";
export {setOnHost} from "./decorator/set-on-host";
export {styleSrc} from "./decorator/style-src";
export {templateSrc} from "./decorator/template-src";
export {emit} from "./decorator/emit";
export {listener} from "./decorator/listener";
export {onBecameVisible} from "./decorator/on-became-visible";
export {onBecameInvisible} from "./decorator/on-became-invisible";
export {onChildrenAdded} from "./decorator/on-children-added";
export {onChildrenRemoved} from "./decorator/on-children-removed";
export {customAttribute} from "./decorator/custom-attribute";
export {dependsOn} from "./decorator/depends-on";
export {hostAttributes} from "./decorator/host-attributes";
export {onAttributeChange} from "./decorator/on-attribute-change";