export enum KeyboardUtil {
	SPACEBAR = " ",
	ENTER = "Enter",
	BACKSPACE = "Backspace",
	TAB = "Tab",
	ALT = "Alt",
	CONTROL = "Control",
	SHIFT = "Shift",
	LEFT_ARROW = "ArrowLeft",
	UP_ARROW = "ArrowUp",
	RIGHT_ARROW = "ArrowRight",
	DOWN_ARROW = "ArrowDown",
	ESCAPE = "Escape",
	ZERO = "0",
	ONE = "1",
	TWO = "2",
	THREE = "3",
	FOUR = "4",
	FIVE = "5",
	SIX = "6",
	SEVEN = "7",
	EIGHT = "8",
	NINE = "9"
}